Use ssl and zip rather than 7zip. 10 times faster.

diff --git a/usrlocalbin/dr_decompress b/usrlocalbin/dr_decompress
--- a/usrlocalbin/dr_decompress
+++ b/usrlocalbin/dr_decompress
@@ -1,11 +1,11 @@
 #!/bin/bash
 set -o nounset
 
-# die MESSAGE 
+# die MESSAGE
 function die {
-   [ -n "$1" ] || { echo "Unexpected error. Exiting."<&2 ; exit 1 ; }
-   
-   echo "$1" <&2
+   [ -n "$1" ] || { echo "Unexpected error. Exiting.">&2 ; exit 1 ; }
+
+   echo "$1" >&2
    exit 1
 }
 
@@ -19,14 +19,14 @@ ARCHIVEPATH="/src/$1"
 
 if [ ! -e "$ARCHIVEPATH" ]; then ls /src ; die "dr_decompress: No such archive: $ARCHIVEPATH"; fi
 if [ ! -d "$DESTFOLDER" ]; then die "dr_decompress: Destination folder does not exist: $DESTFOLDER"; fi
- 
+
 # default to empty string if doesn't exist, then test for empty string.
-if [ -n "${PASS-}" ]; then 
-   PASSCMD="-p${PASS}"; 
+if [ -n "${PASS-}" ]; then
+   openssl aes-256-cbc -d -in "${ARCHIVEPATH}" -k ${PASS} | tar xz -C "${DESTFOLDER}" > /dev/null 2>&1
+   #> /dev/null 2>&1
 else
-   PASSCMD="-p\"\""
    echo "WARNING: No password supplied.">&2
+   tar xzf "${ARCHIVEPATH}" -C "${DESTFOLDER}"
 fi
 
-7za x -so "${PASSCMD}" "${ARCHIVEPATH}" 2>/dev/null | tar xf - -C "${DESTFOLDER}" >/dev/null 2>&1
 if [ $? -ne 0 ]; then die "Failed to decompress archive. The password may be incorrect!"; fi
